(define (domain goldminer)
    (:requirements :conditional-effects :derived-predicates :negative-preconditions :typing :disjunctive-preconditions)
    (:constants f6-4f - LOC)
    (:types LOC)
    (:predicates (Y-Oclear_f6-4f) (arm-empty) (bomb-at ?x - LOC)  (clear ?x - LOC)  (connected ?x - LOC ?y - LOC)  (gold-at ?x - LOC)  (hard-rock-at ?x - LOC)  (holds-bomb) (holds-gold) (holds-laser) (laser-at ?x - LOC)  (robot-at ?x - LOC)  (soft-rock-at ?x - LOC)  (val-Oclear_f6-4f) (val-clear_f6-4f) (val-holds-gold) (val-holds-gold-and-Oclear_f6-4f))
    (:derived (val-Oclear_f6-4f) (or (val-clear_f6-4f) (Y-Oclear_f6-4f)))
     (:derived (val-clear_f6-4f) (clear f6-4f))
     (:derived (val-holds-gold) (holds-gold))
     (:derived (val-holds-gold-and-Oclear_f6-4f) (and (val-holds-gold) (val-Oclear_f6-4f)))
    (:action detonate-bomb
        :parameters (?x - LOC ?y - LOC)
        :precondition (and (robot-at ?x) (holds-bomb) (connected ?x ?y) (soft-rock-at ?y))
        :effect (and (not (holds-bomb)) (arm-empty) (clear ?y) (not (soft-rock-at ?y)) (when (not (val-Oclear_f6-4f)) (not (Y-Oclear_f6-4f))) (when (val-Oclear_f6-4f) (Y-Oclear_f6-4f)))
    )
     (:action fire-laser
        :parameters (?x - LOC ?y - LOC)
        :precondition (and (robot-at ?x) (holds-laser) (connected ?x ?y))
        :effect (and (clear ?y) (not (soft-rock-at ?y)) (not (gold-at ?y)) (not (hard-rock-at ?y)) (when (not (val-Oclear_f6-4f)) (not (Y-Oclear_f6-4f))) (when (val-Oclear_f6-4f) (Y-Oclear_f6-4f)))
    )
     (:action move
        :parameters (?x - LOC ?y - LOC)
        :precondition (and (robot-at ?x) (connected ?x ?y) (clear ?y))
        :effect (and (robot-at ?y) (not (robot-at ?x)) (when (not (val-Oclear_f6-4f)) (not (Y-Oclear_f6-4f))) (when (val-Oclear_f6-4f) (Y-Oclear_f6-4f)))
    )
     (:action pick-gold
        :parameters (?x - LOC)
        :precondition (and (robot-at ?x) (arm-empty) (gold-at ?x))
        :effect (and (not (arm-empty)) (holds-gold) (when (not (val-Oclear_f6-4f)) (not (Y-Oclear_f6-4f))) (when (val-Oclear_f6-4f) (Y-Oclear_f6-4f)))
    )
     (:action pickup-bomb
        :parameters (?x - LOC)
        :precondition (and (robot-at ?x) (bomb-at ?x) (arm-empty))
        :effect (and (not (arm-empty)) (holds-bomb) (when (not (val-Oclear_f6-4f)) (not (Y-Oclear_f6-4f))) (when (val-Oclear_f6-4f) (Y-Oclear_f6-4f)))
    )
     (:action pickup-laser
        :parameters (?x - LOC)
        :precondition (and (robot-at ?x) (laser-at ?x) (arm-empty))
        :effect (and (not (arm-empty)) (holds-laser) (not (laser-at ?x)) (when (not (val-Oclear_f6-4f)) (not (Y-Oclear_f6-4f))) (when (val-Oclear_f6-4f) (Y-Oclear_f6-4f)))
    )
     (:action putdown-laser
        :parameters (?x - LOC)
        :precondition (and (robot-at ?x) (holds-laser))
        :effect (and (arm-empty) (not (holds-laser)) (laser-at ?x) (when (not (val-Oclear_f6-4f)) (not (Y-Oclear_f6-4f))) (when (val-Oclear_f6-4f) (Y-Oclear_f6-4f)))
    )
)